@startuml
' If no parent then collection
entity Folder {
   _id: objectId
   parent_id?: int
   name: string
}

entity Request {
   _id: objectId
   folder_id: objectId
   request_method_id: objectId
   name: string
   url?: string
}

entity RequestMethod {
   _id: objectId
   name: string
}

Folder "0..*" --- "0..1" Folder
Folder "1" --- "0..*" Request
Request "1" --- "0..*" RequestMethod

@enduml
