### 

@REQUEST = {{API_URL}}/request
@folder_id = 69e3feac9e88e0e081baa349
@id = 69e563ccbd1538833bc57e21
@method_id = 69e0da060e2bbf6dce243090


### Get by folder_id

# // # @prompt folder_id

GET {{REQUEST}}/folder_id/{{folder_id}} HTTP/1.1


### Create

POST {{REQUEST}} HTTP/1.1

{
  "folder_id": "{{folder_id}}",
  "name": "RERE",
  "request_method_id": "{{method_id}}",
  "url": "test"
}


### Delete

DELETE {{REQUEST}}/{{id}} HTTP/1.1
